version: '3.9'
services:
  mongoDB:
    container_name: mongoDB
    image: mongo
    expose:
      - 27017
  api:
    container_name: api
    build: ./api
    expose:
      - 8000
    links:
      - mongoDB
    volumes:
      - ./api:/usr/scr/app
  client:
    container_name: client
    build: ./client
    expose:
      - 3000
    volumes:
      - ./client:/usr/src/app
  nginx:
    build:  ./nginx
    ports:
      - 80:80
    links:
      - api
      - client
    restart: always
